# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801a4da83dff8193746ca74f275f30b40292b673ef2fc00df77f9ecabed50c9b056291e6650134ef94b4cb100808649dca0224f7156c198e3c2e392928804728

test:
  secret_key_base: 266b98263b5621601a5f117a6a8e9b8929e86dd807681d1b77bdb6af312b8b1c74518282d524f159ebb42f8ba4ff27edb90717e24185eba14c09150faa9dcae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
